secretary/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),  
    path('accounts/', include('django.contrib.auth.urls')),  
    path('', RedirectView.as_view(url='/web/diary')),  
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('diary/', views.DiaryListView.as_view()),
    path('diary/add/', views.DiaryCreate.as_view()),
    path('diary/<int:pk>/update/', views.DiaryUpdate.as_view()),
    path('diary/<int:pk>/delete/', views.DiaryDelete.as_view()),  
    path('money', views.MoneyListView.as_view()),
    path('money/add/', views.MoneyCreate.as_view()),
    path('money/<int:pk>/update/', views.MoneyUpdate.as_view()),
    path('money/<int:pk>/delete/', views.MoneyDelete.as_view()),  
]

web/models.py
# -*- coding: UTF-8 -*-
from django.db import models

# 日誌
class Diary(models.Model):
        memo = models.TextField(verbose_name='內容')
        time = models.DateTimeField(auto_now_add=True)

        def __str__(self):
                return self.memo

# 帳目
class Money(models.Model):
        CHOICES = (
                (1, "飲食"),
                (2, "衣服"),
                (3, "交通"),
                (4, "教育"),
                (5, "娛樂"),
                (6, "其它"),
        )    
        item = models.CharField(max_length=30, verbose_name='項目')
        kind = models.IntegerField(default=0, choices=CHOICES, verbose_name='類別')
        price = models.IntegerField(default=0, verbose_name='金額')
        time = models.DateTimeField(auto_now_add=True)

        def __str__(self):
                return self.item
          
        

web/views.py
from django.shortcuts import render
from django.views import generic
from .models import Diary, Money
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
class DiaryListView(LoginRequiredMixin, generic.ListView):
    model = Diary
    ordering = ['-time']
    login_url = '/accounts/login/'
        
class DiaryCreate(CreateView):
    model = Diary
    fields = '__all__'
    success_url = "/"
    template_name = 'form.html'    

class DiaryUpdate(UpdateView):
    model = Diary
    fields = '__all__'
    success_url = "/"   
    template_name = 'form.html'      

class DiaryDelete(DeleteView):
    model = Diary
    success_url = "/"
    template_name = 'confirm_delete.html'    
    
class MoneyListView(generic.ListView):
    model = Money
    ordering = ['-time']
        
class MoneyCreate(CreateView):
    model = Money
    fields = '__all__'
    success_url = "/web/money"
    template_name = 'form.html'

class MoneyUpdate(UpdateView):
    model = Money
    fields = '__all__'
    success_url = "/web/money"    
    template_name = 'form.html'      

class MoneyDelete(DeleteView):
    model = Money
    success_url = "/web/money"   
    template_name = 'confirm_delete.html'       

web/templates/base.html
<!DOCTYPE html>
<!--
Template Name: Ostenien
Author: <a href="http://www.os-templates.com/">OS Templates</a>
Author URI: http://www.os-templates.com/
Licence: Free to use under our free template licence terms
Licence URI: http://www.os-templates.com/template-terms
-->
<html>
<head>
<title>我的隨身秘書</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
{% load static %}
<link rel="stylesheet" href="{% static 'css/layout.css' %}">
</head>
<body>
<body id="top">
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row0">
  <header id="header" class="hoc clear"> 
    <!-- ################################################################################################ -->
    <div id="logo">
      <h1>我的隨身秘書</h1>
    </div>
    <!-- ################################################################################################ -->
  </header>
</div>
<div class="wrapper row1">
  {% if user.is_authenticated %}   
  <nav id="mainav" class="hoc clear"> 
    <!-- ################################################################################################ -->
    <ul class="clear">
        <li><a href="/web/diary">日記</a></li>
        <li><a href="/web/diary/add">寫日誌</a></li>
        <li><a href="/web/money">帳本</a></li>           
        <li><a href="/web/money/add">記帳</a></li> 
        <li><a href="/accounts/logout">登出</a></li>
    </ul>
    <!-- ################################################################################################ -->
  </nav>
  {% endif %}  
</div>
    <!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row3">
  <main class="hoc container clear"> 
    <!-- main body -->
    <!-- ################################################################################################ -->
    <div class="group">
      <h3>
     {% block content %}
     {% endblock %}        
      </h3>

    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>

    <!-- ################################################################################################ -->
<div class="wrapper row6">
  <div id="copyright" class="clear"> 
    <!-- ################################################################################################ -->
    <p class="fl_left">Copyright &copy; 2018 - All Rights Reserved - 網站開發：高慧君</p>
    <p class="fl_right">Template by <a target="_blank" href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
    <!-- ################################################################################################ -->
  </div>
</div>
<script src="/static/js/jquery.min.js"></script> 
<script src="/static/js/jquery.mobilemenu.js"></script>  
</body>
</html>

web/templates/confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>刪除記錄</h1>

<p>您確定要刪除這筆記錄嗎?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="是的，我要刪除" />
</form>

{% endblock %}

web/templates/form.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="送出" />
    
</form>
{% endblock %}

web/templates/web/diary_list.html
{% extends "base.html" %}

{% block content %}
        我的日誌：<BR>
        <table>
          <tr><td>時間</td><td>項目</td><td>功能</td></tr>
{% for diary in diary_list %}          
          <tr><td>({{diary.time| date:"l"}}){{diary.time}}</td></td><td><a href="diary/{{diary.id}}/update/">{{diary.memo}}</a></td><td><a href="diary/{{diary.id}}/delete/">刪除</a></td></tr>
{% endfor %}           
        </table>
         


<h1></h1>


<BR>

{% endblock %}

web/templates/web/money_list.html
{% extends "base.html" %}

{% block content %}
        我的帳本：<BR>
        <table>
          <tr><td>時間</td><td>項目</td><td>功能</td></tr>
{% for money in money_list %}          
          <tr><td>({{money.time| date:"l"}}){{money.time}}</td></td><td><a href="money/{{money.id}}/update/">{{money.item}}--{{money.get_kind_display}}--{{money.price}}</a></td><td><a href="money/{{money.id}}/delete/">刪除</a></td></tr>
{% endfor %}           
       </table>
         


<h1></h1>


<BR>

{% endblock %}